name: test

on:
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4     
    - name: install depencencies
      run: npm ci
    - name: install playwright dependencies
      run: npx playwright install --with-deps
    - name: run playwright test
      run: npm test
      env:
        SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SENDER_CHAIN: ${{ secrets.SENDER_CHAIN }}
        RECEIVER_CHAIN: ${{ secrets.RECEIVER_CHAIN }}
    - name: upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 30
    - name: deploy to github pages
      if: github.actor != 'dependabot[bot]'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: playwright-report
